### ISSUE TITLE
inav setup

### ISSUE THREAD

**Issue by kazuyahirotsu** [bird-org/AstralProject#7]

**Comment by 0sora9** [comment]
inavで姿勢キャリブレーションは終わってるんだけど、ARMのテストでモーター動かず原因不明。
inav上でスロットル上げても反応しない。
---
・バッテリー繋いでいる
・バッテリー繋ぐと起動音鳴る+モーターがポジショニングで少し動く(モーターまで認識できてる)
・ESCプロトコル、マグネット数も正しい
・FCとESCの配線もあってる
・gps無しでもARMする設定にしている
もしかしたらの懸念点
・ESCどこか焼けている→火水木金で追加調達
・バッテリー劣化？
・プロポがないと作動しない？
・firmware
---
はんだ付け直し，設定し直しで対応するか？
esc新しいの用意するか

**Comment by 0sora9** [comment]
原因はfc→escの配線カプラーでの取り付け方向(上下)のミスによる接触不良でした
